server:
  port: 8082

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
spring:
  data:
    mongodb:
      uri: mongodb+srv://${DATABASE_USER:admin}:${DATABASE_PASSWORD:admin}@${DATABASE_HOST:localhost}/${DATABASE_NAME:payment}?retryWrites=true&w=majority
      # uri: mongodb://localhost:27017/food-payment
  application:
    name: Good Food Payment Service

