apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DATABASE_HOST: Z29vZGZvb2QtbW9uZ28uaGVmeGQwbS5tb25nb2RiLm5ldA==
  DATABASE_PORT: MjcwMTc=
  DATABASE_NAME: Z29vZGZvb2QtbW9uZ28=
  DATABASE_USER: YWRtaW4=
  DATABASE_PASSWORD: YWRtaW4=
