apiVersion: v1
kind: Service
metadata:
  name: svc-goodfood-payment-postech-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: goodfood-payment-postech